### ISSUE TITLE
Antibody setup

### ISSUE THREAD

**Issue by Sasquiche** [jonleopard/dotfiles#1]
Hello!

Your dotfile really is a great source for a beginner to learn from. I find myself going back to it and learning new configuration for me own dotfile.

I wanted to ask if your current set up of antibody overpopulates your `fpath` with each plugin destination and if you've experienced any duplications on your `fpath` as well?

**Comment by jonleopard** [comment]
Hi @Sasquiche! Glad to hear this repo has helped you a little bit :)

It looks like I have one duplicate in my `fpath`. If you are worried about duplicates in your `path` or `fpath`, check out this blog post: https://www.linuxjournal.com/content/removing-duplicate-path-entries

I'm also not sure what you mean by 'overpopulates'? 


Here's what my `fpath` looks like:
```
/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.7.1/share/zsh/functions
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-mafredri-SLASH-zsh-async
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-rupa-SLASH-z
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-felixr-SLASH-docker-zsh-completion/src
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-felixr-SLASH-docker-zsh-completion
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions/src
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-pure
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting
/Users/jon/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search
```

**Comment by Sasquiche** [comment]
Thank you for the additional information. 

It's clarified my confusion about duplicate items within a `*PATH` variable.

I misspoke when I said "overpopulate". I had meant if your `fpath` was being filled with the full path name of each plugin after `antibody bundle`:

`/Users/you/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zdharma-SLASH-fast-syntax-highlighting`

 Rather than a single entry for the plugins home directory: 
`/Users/you/Library/Caches/antibody`

But in the time writing this I just realized that the former has to be the case, as `fpath` only goes 1 lvl deep when reading! It's silly that I missed that.

You definitely answered my question anyways! Thanks for taking the time to clarify.
